// I-am-autogenerated

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const logFilePath = path.join(__dirname, "logs.txt");

/**
 * Logs a message with a timestamp
 * @param {string} level - Log level (INFO, WARN, ERROR)
 * @param {string} message - Log message
 * @param {object} context - Additional context information
 */
export function log(level, message, context = {}) {
  const timestamp = new Date().toISOString();
  const logEntry = `${timestamp} [${level}] ${message} ${JSON.stringify(context)}\n`;

  // Log to console
  console.log(logEntry.trim());

  // Append to log file
  fs.appendFileSync(logFilePath, logEntry);
}
